# Use Ubuntu as base image
FROM ubuntu:latest

# Install Python 3 and pip
RUN apt-get update && \
    apt-get install -y python3 python3-pip git sudo curl python3.12-venv && \
    apt-get clean

# Install OpenSSH client
RUN apt-get update && apt-get install -y openssh-client && \
    apt-get clean

# Create a user with arguments passed in
ARG USERNAME=user
ARG PASSWORD=password
RUN useradd -rm -d /home/$USERNAME -s /bin/bash -g root -G sudo -u 1001 $USERNAME && \
    echo "$USERNAME:$PASSWORD" | chpasswd && \
    mkdir /var/run/sshd

# Switch to user and set the working directory
USER $USERNAME
WORKDIR /home/$USERNAME

RUN git clone https://github.com/calc1f4r/SSH-Bruteforcer.git && \
    cd SSH-Bruteforcer && \
    python3 -m venv venv && \
    . venv/bin/activate && \
    pip3 install -r requirements.txt && \
    curl -O https://raw.githubusercontent.com/kkrypt0nn/wordlists/main/wordlists/usernames/multiple_sources_users.txt && \
    curl -O https://raw.githubusercontent.com/kkrypt0nn/wordlists/main/wordlists/passwords/darkweb_2017.txt

CMD tail -f /dev/null
