# Use Ubuntu as base image
FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive
# Install OpenSSH client
RUN apt-get update && apt-get install -y python3-pip python3-dev gcc git libffi-dev libssl-dev libxml2-dev libxslt1-dev zlib1g-dev

RUN git clone https://github.com/faucetsdn/ryu.git && \
    cd ryu && \
    pip install .

RUN git clone https://github.com/maxbekh/sshbruteforce_sds.git

CMD tail -f /dev/null
