# Use Ubuntu as base image
FROM ubuntu:latest

# Install Python 3 and pip
RUN apt-get update && \
    apt-get install -y python3 python3-pip git sudo curl wget python3.12-venv nmap net-tools iptables openssh-client && \
    apt-get clean

RUN git clone https://github.com/maxbekh/sshbruteforce_sds.git && \
    cd sshbruteforce_sds && \
    python3 -m venv venv && \
    . venv/bin/activate && \
    pip3 install -r requirements.txt

CMD tail -f /dev/null
